# **Numpy**

In [42]:
from numpy import *

In [15]:
li = [1,2,3]
a = array(li,dtype=int32)  #creation of 1-d array from a list
print(a)
print(a.shape)

[1 2 3]
(3,)


In [16]:
 b = array([[2,3,5,4],[5,3,5,1],[1,3,5,7]],dtype= int32) #creation of np 2-d array 
 print(b.shape)
 print(b)

(3, 4)
[[2 3 5 4]
 [5 3 5 1]
 [1 3 5 7]]


# **Random Function**

In [38]:
random.rand(100,100) # genrates a random array from 0 to 1

array([[0.99602303, 0.42988203, 0.16619774, ..., 0.49480079, 0.51301445,
        0.67124767],
       [0.38374435, 0.24686102, 0.52125746, ..., 0.51000234, 0.4892012 ,
        0.81233482],
       [0.26115183, 0.54047365, 0.91401002, ..., 0.93248812, 0.03443322,
        0.84810383],
       ...,
       [0.23707226, 0.39399515, 0.83101716, ..., 0.52784536, 0.63388967,
        0.16350682],
       [0.16977092, 0.4321674 , 0.3930735 , ..., 0.76524141, 0.07785841,
        0.22811553],
       [0.44857729, 0.30297444, 0.70346769, ..., 0.51637355, 0.01223145,
        0.48229033]])

In [57]:
print(random.rand(5),"\n\n\n")
print(random.rand(5,6),"\n\n\n")
#random.rand((2,3)) #throws an error if tupple passed
print(random.random((2,3))) # can pass tupple also

[0.40105356 0.28340917 0.1751021  0.60117257 0.04935315] 



[[0.83465602 0.628628   0.91599034 0.04421589 0.03066511 0.66770446]
 [0.19486197 0.88611327 0.03245809 0.67818622 0.78965218 0.261542  ]
 [0.13083909 0.00440578 0.95284876 0.68641501 0.60757596 0.25835124]
 [0.95139537 0.52912657 0.12625545 0.87824777 0.43945779 0.98200287]
 [0.75731018 0.85391635 0.46886287 0.33871384 0.08481458 0.44855416]] 



[[0.87674612 0.59095092 0.23578433]
 [0.66866036 0.93303216 0.64574288]]


In [58]:
print(random.randint(low=55,high=999,size=(3,5,),dtype=int32)) # low--> start ,hig-->end,size-->tupple/int for size ,dtype-->(optional)

[[498 736 211  65 339]
 [150 624 989 806 485]
 [791 187 661 953 945]]


In [52]:
print(random.choice([6,7,8,9,100],(2,3))) 
"""parameters 
a--> int or list 
 size = int or tupple 
replace = T/F--> if you want to use element from passed a manny times  
p --> probabilties of each instances passed in the a"""

[[  6 100   9]
 [100   8   7]]


# **Functions**

In [31]:
print("identity : ",identity(3,dtype=int32),"\n\n") #identity matrix 
#identity(3,4) will throw an error
print("eye : ",eye(3,4,dtype=int32)) #identity matrix can also create identity of other then sqare matrix

identity :  [[1 0 0]
 [0 1 0]
 [0 0 1]] 


eye :  [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


# **Slicing in numpy**


In [37]:
random.random((3,3))

array([[0.0124093 , 0.30900893, 0.76291199],
       [0.81074342, 0.1697538 , 0.76474941],
       [0.93424472, 0.37171087, 0.09344349]])

In [35]:
b = array([[2,3,5,4],[5,3,5,1],[1,3,5,7]],dtype= int32)
print(b[::2,::3])
print(b[::2,[0,-1]])

[[2 4]
 [1 7]]
[[2 4]
 [1 7]]
